/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hotelmanagement.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Customer service. Represents a row in the &quot;Hotel_Customer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>hotelmanagement.services.model.impl.CustomerModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>hotelmanagement.services.model.impl.CustomerImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Customer
 * @generated
 */
@ProviderType
public interface CustomerModel extends BaseModel<Customer> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a customer model instance should use the {@link Customer} interface instead.
	 */

	/**
	 * Returns the primary key of this customer.
	 *
	 * @return the primary key of this customer
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this customer.
	 *
	 * @param primaryKey the primary key of this customer
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the customer ID of this customer.
	 *
	 * @return the customer ID of this customer
	 */
	public int getCustomerId();

	/**
	 * Sets the customer ID of this customer.
	 *
	 * @param customerId the customer ID of this customer
	 */
	public void setCustomerId(int customerId);

	/**
	 * Returns the first name of this customer.
	 *
	 * @return the first name of this customer
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this customer.
	 *
	 * @param firstName the first name of this customer
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the middle name of this customer.
	 *
	 * @return the middle name of this customer
	 */
	@AutoEscape
	public String getMiddleName();

	/**
	 * Sets the middle name of this customer.
	 *
	 * @param middleName the middle name of this customer
	 */
	public void setMiddleName(String middleName);

	/**
	 * Returns the last name of this customer.
	 *
	 * @return the last name of this customer
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this customer.
	 *
	 * @param lastName the last name of this customer
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the email of this customer.
	 *
	 * @return the email of this customer
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this customer.
	 *
	 * @param email the email of this customer
	 */
	public void setEmail(String email);

	/**
	 * Returns the mobile of this customer.
	 *
	 * @return the mobile of this customer
	 */
	@AutoEscape
	public String getMobile();

	/**
	 * Sets the mobile of this customer.
	 *
	 * @param mobile the mobile of this customer
	 */
	public void setMobile(String mobile);

	/**
	 * Returns the age of this customer.
	 *
	 * @return the age of this customer
	 */
	public int getAge();

	/**
	 * Sets the age of this customer.
	 *
	 * @param age the age of this customer
	 */
	public void setAge(int age);

	/**
	 * Returns the desc of this customer.
	 *
	 * @return the desc of this customer
	 */
	@AutoEscape
	public String getDesc();

	/**
	 * Sets the desc of this customer.
	 *
	 * @param desc the desc of this customer
	 */
	public void setDesc(String desc);

}