/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ROOMSERVICES.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Rooms service. Represents a row in the &quot;Infy_Rooms&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ROOMSERVICES.model.impl.RoomsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ROOMSERVICES.model.impl.RoomsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Rooms
 * @generated
 */
@ProviderType
public interface RoomsModel extends BaseModel<Rooms> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rooms model instance should use the {@link Rooms} interface instead.
	 */

	/**
	 * Returns the primary key of this rooms.
	 *
	 * @return the primary key of this rooms
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this rooms.
	 *
	 * @param primaryKey the primary key of this rooms
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the room ID of this rooms.
	 *
	 * @return the room ID of this rooms
	 */
	public int getRoomId();

	/**
	 * Sets the room ID of this rooms.
	 *
	 * @param roomId the room ID of this rooms
	 */
	public void setRoomId(int roomId);

	/**
	 * Returns the room type ID of this rooms.
	 *
	 * @return the room type ID of this rooms
	 */
	public int getRoomTypeId();

	/**
	 * Sets the room type ID of this rooms.
	 *
	 * @param roomTypeId the room type ID of this rooms
	 */
	public void setRoomTypeId(int roomTypeId);

	/**
	 * Returns the amenities ID of this rooms.
	 *
	 * @return the amenities ID of this rooms
	 */
	public int getAmenitiesId();

	/**
	 * Sets the amenities ID of this rooms.
	 *
	 * @param amenitiesId the amenities ID of this rooms
	 */
	public void setAmenitiesId(int amenitiesId);

	/**
	 * Returns the room name of this rooms.
	 *
	 * @return the room name of this rooms
	 */
	@AutoEscape
	public String getRoomName();

	/**
	 * Sets the room name of this rooms.
	 *
	 * @param roomName the room name of this rooms
	 */
	public void setRoomName(String roomName);

	/**
	 * Returns the total rooms available of this rooms.
	 *
	 * @return the total rooms available of this rooms
	 */
	public int getTotalRoomsAvailable();

	/**
	 * Sets the total rooms available of this rooms.
	 *
	 * @param totalRoomsAvailable the total rooms available of this rooms
	 */
	public void setTotalRoomsAvailable(int totalRoomsAvailable);

	/**
	 * Returns the create date of this rooms.
	 *
	 * @return the create date of this rooms
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this rooms.
	 *
	 * @param createDate the create date of this rooms
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the create by of this rooms.
	 *
	 * @return the create by of this rooms
	 */
	@AutoEscape
	public String getCreateBy();

	/**
	 * Sets the create by of this rooms.
	 *
	 * @param createBy the create by of this rooms
	 */
	public void setCreateBy(String createBy);

	/**
	 * Returns the update date of this rooms.
	 *
	 * @return the update date of this rooms
	 */
	public Date getUpdateDate();

	/**
	 * Sets the update date of this rooms.
	 *
	 * @param updateDate the update date of this rooms
	 */
	public void setUpdateDate(Date updateDate);

	/**
	 * Returns the updated by of this rooms.
	 *
	 * @return the updated by of this rooms
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this rooms.
	 *
	 * @param updatedBy the updated by of this rooms
	 */
	public void setUpdatedBy(String updatedBy);

}