/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ROOMSERVICES.model;

import ROOMSERVICES.service.persistence.RoomTypePK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RoomType service. Represents a row in the &quot;Infy_RoomType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ROOMSERVICES.model.impl.RoomTypeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ROOMSERVICES.model.impl.RoomTypeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RoomType
 * @generated
 */
@ProviderType
public interface RoomTypeModel extends BaseModel<RoomType> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a room type model instance should use the {@link RoomType} interface instead.
	 */

	/**
	 * Returns the primary key of this room type.
	 *
	 * @return the primary key of this room type
	 */
	public RoomTypePK getPrimaryKey();

	/**
	 * Sets the primary key of this room type.
	 *
	 * @param primaryKey the primary key of this room type
	 */
	public void setPrimaryKey(RoomTypePK primaryKey);

	/**
	 * Returns the room type ID of this room type.
	 *
	 * @return the room type ID of this room type
	 */
	public int getRoomTypeId();

	/**
	 * Sets the room type ID of this room type.
	 *
	 * @param roomTypeId the room type ID of this room type
	 */
	public void setRoomTypeId(int roomTypeId);

	/**
	 * Returns the room type of this room type.
	 *
	 * @return the room type of this room type
	 */
	@AutoEscape
	public String getRoomType();

	/**
	 * Sets the room type of this room type.
	 *
	 * @param RoomType the room type of this room type
	 */
	public void setRoomType(String RoomType);

}